module.exports = {
  code: 200,
  data: [
    {
      id: 1,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: 1,
      deptName: "部门结构1-1",
      occupation: "web开发",
      hobby: "旅游",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 2,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: 2,
      deptName: "部门结构2-1",
      occupation: "web开发",
      hobby: "旅游",
      enable: false,
      createTime: new Date().getTime(),
    },
    {
      id: 3,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: 3,
      deptName: "部门结构3-1",
      occupation: "web开发",
      hobby: "111",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 4,
      username: "falcon",
      email: "falcon@126.com",
      sex: "1",
      dept: 4,
      deptName: "部门结构4-1",
      occupation: "web开发",
      hobby: "112",
      enable: false,
      createTime: new Date().getTime(),
    },
    {
      id: 5,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: 2,
      deptName: "部门结构2-1",
      occupation: "web开发",
      hobby: "113",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 6,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: 5,
      deptName: "部门结构4-2",
      occupation: "web开发",
      hobby: "",
      enable: false,
      createTime: new Date().getTime(),
    },
  ],
  treeData: [
    {
      id: 1,
      label: "部门结构1-1",
      children: [
        {
          id: 2,
          label: "部门结构2-1",
          children: [
            {
              id: 3,
              label: "部门结构3-1",
              children: [
                {
                  id: 4,
                  label: "部门结构4-1",
                },
                {
                  id: 5,
                  label: "部门结构4-2",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  msg: "获取用户数据成功",
};
