module.exports = {
  tableData: {
    code: 200,
    data: [
      {
        id: 1,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 2,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 3,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 4,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 5,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 6,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
      {
        id: 7,
        username: "falcon",
        email: "falcon@126.com",
        sex: "0",
        dept: "产业互联网事业部/研发中心",
        occupation: "web开发",
      },
    ],
    msg: "获取用户数据成功",
  },
};
