module.exports = {
  code: 200,
  data: [
    {
      id: 1,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "旅游",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 2,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "旅游",
      enable: false,
      createTime: new Date().getTime(),
    },
    {
      id: 3,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 4,
      username: "falcon",
      email: "falcon@126.com",
      sex: "1",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "",
      enable: false,
      createTime: new Date().getTime(),
    },
    {
      id: 5,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "",
      enable: true,
      createTime: new Date().getTime(),
    },
    {
      id: 6,
      username: "falcon",
      email: "falcon@126.com",
      sex: "0",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "",
      enable: false,
      createTime: new Date().getTime(),
    },
    {
      id: 7,
      username: "falcon",
      email: "falcon@126.com",
      sex: "1",
      dept: "产业互联网事业部/研发中心",
      occupation: "web开发",
      hobby: "",
      enable: true,
      createTime: new Date().getTime(),
    },
  ],
  msg: "获取用户数据成功",
};
